### ISSUE TITLE
Doesn't seem to work for now, even in CMD

### ISSUE THREAD

**Issue by JoseHidalgo** [Lordmau5/spd-issues#1]
Hi, following your suggestions, I have opened a W7 CMD prompt and typed the following line:
SpotifyDownloader.exe -u MYUSERNAME -p MYPASSWORD -l https://play.spotify.com/user/MYUSERNAME/playlist/MYPLAYLISTNUMBER

I've also tried the following syntax:
SpotifyDownloader.exe -u MYUSERNAME -p MYPASSWORD -l spotify:playlist:MYPLAYLISTNUMBER

(BTW, Spotify no longer allows URIs to appear, I have nothing in my context menu which makes it more difficult. Why not use URLs instead ?)

ANYWAY. Instead of anything happening in the CMD prompt, the GUI launches automatically, then I got the following code IN the GUI window, not in the CMD:

> ws@0.6.5 install C:\Program Files\Spotify Downloader\node_modules\spotify-web\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Program Files\Spotify Downloader\node_modules\spotify-web\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild ) 
node-id3@0.0.4 node_modules\node-id3

httpreq@0.4.16 node_modules\httpreq
async@0.9.2 node_modules\async
colors@1.1.2 node_modules\colors
coffee-script@1.10.0 node_modules\coffee-script
commander@2.9.0 node_modules\commander
â””â”€â”€ graceful-readlink@1.0.1
mkdirp@0.5.1 node_modules\mkdirp
â””â”€â”€ minimist@0.0.8
lodash@3.10.1 node_modules\lodash

spotify-web@1.3.2 node_modules\spotify-web
â”œâ”€â”€ debug@2.1.3 (ms@0.7.0)
â”œâ”€â”€ readable-stream@1.0.33 (string_decoder@0.10.31, isarray@0.0.1, core-util-is@1.0.2, inherits@2.0.1)
â”œâ”€â”€ ws@0.6.5 (options@0.0.6, ultron@1.0.2, nan@1.4.3)
â”œâ”€â”€ superagent@0.21.0 (extend@1.2.1, cookiejar@2.0.1, methods@1.0.1, reduce-component@1.0.1, mime@1.2.11, component-emitter@1.1.2, qs@1.2.0, readable-stream@1.0.27-1, formidable@1.0.14, form-data@0.1.3)
â”œâ”€â”€ cheerio@0.18.0 (entities@1.1.1, lodash@2.4.2, dom-serializer@0.0.1, CSSselect@0.4.1, htmlparser2@3.8.3)
â””â”€â”€ protobufjs@2.2.1 (ascli@1.0.0, bytebuffer@2.3.2)

... and that's all. Any ideas ? Thanks.

**Comment by Lordmau5** [comment]
You are not running it with the code of my repo and how I stated it in my readme, but rather try to run it via. dekiller's code.

You should still be able to get URIs, the context menu *should* show it. It does for me still:
![image](https://i.lordmau5.com/1460131349-844.png)
*(German, but you should get the drill)*

As mentioned already, the code will be reworked a bit, so you don't have to post the stuff seperately (as in, `playlist user` and `playlist id`)
Those will be replaced by just one parameter, which is the full *URI*.
(Also allows for downloading single albums or tracks)

**Comment by JoseHidalgo** [comment]
OK, I have made sure that the code was from your repository this time  : https://github.com/Lordmau5/spotify-playlist-downloader

I have extracted the files in C:\Program Files\Spotify Downloader
I have installed (npm install) : apparent success
I hate tried to run it : node main.js -u UserXYZ -p PlaylistNUMBER (end of the URL)

Here's the error :
Downloader App started..
Error logging in... (Error: invalid_credentials)

This looks normal to me, since at no point have I been asked to enter my password !
So where should I put it ? In you sintax I only see UserXYZ which should be my user name, so...

**Comment by Lordmau5** [comment]
You need to edit the main.js (for now) to have your username in there.

As I said, the rework is going to have decent parameters again - the current readme is a bit of a mess as well...

So yea, edit the main.js with your login username + password, then run that command again, then post the errors you have again :P

**Comment by JoseHidalgo** [comment]
Thanks :) Here's the new output:
Downloader App started..
 - Getting Playlist Data
Playlist data error... Error: Client error: Bad Request (400)

**Comment by JoseHidalgo** [comment]
... bump ?...

**Comment by Lordmau5** [comment]
Ah, sorry, completely forgot about that.

What was the input you did in the commandline?
`node main.js <...>`

**Comment by JoseHidalgo** [comment]
The input was the same as previously:
node main.js -u UserXYZ -p PlaylistNUMBER (end of the URL)
Ex: if the URL is https://play.spotify.com/user/UserXYZ/playlist/PlaylistNUMBER , then I will just take the PlaylistNUMBER part.

**Comment by serjum** [comment]
-u USERNAME (spotigy login)
-p PASSWORD
-l  playlist

Ex:
node main.js -u myuser -p mypassword -l spotify:user:spotify:playlist:4ecQaDJHF55Ls9m2lKIXbI

**Comment by JoseHidalgo** [comment]
Really ? Because...
error: unknown option '-l'
Guys, please agree on something. Thank you. :)

**Comment by Lordmau5** [comment]
As I said - bit of rework (hopefully this weekend), and the username and password parameters will come back, together with a `-i` parameter, that allows input for raw URIs (yes, even tracks and albums)

**Comment by serjum** [comment]
@JoseHidalgo ,  this fork for now don't have option for password. You can wait for his updates on this  weekend, or try to install my fork. Last weekend I have updated it and tested on windows from cmd, the installation process is described as response for your request here -> https://github.com/serjum/spotify-playlist-downloader/pull/1#issuecomment-207675513

**Comment by Lordmau5** [comment]
Quick heads-up to @serjum , because I don't know of any other way to contact you.

I have quickly made a Gitter.im room that I have invited you and dekiller (the guy who did the GUI wrapper for it), since I'd like to talk a few things through with you two.
It seems that you didn't use Gitter before, and I'd need a mail to invite you to it, or you need to hook up your account with Gitter... that should work too :P

**Comment by JoseHidalgo** [comment]
Guys, so far I can't make it work, sorry. :(

I've tried with serjum's fork and his install instructions, but i'm doing something wrong.
I don't understand this part : "from Node.js command prompt go to unzipped folder and do node install". I'm just using a regular command prompt from the unzipped folder. So every attempt to "node install" results in an error:
module.js:327 throw error;
^
Error: Cannot find module 'C:\Program Files\Spotify Downloader\install'

On the other hand, with the previous Lordmau5's fork I somehow managed to get it right previously, because I managed to launch the downloader itself, like explained previously in this thread. It's just that right now it doesn't work yet (like explained previously too).

So ultimately I'm hoping to test the new Lordmau5's update with -p and -i parameters. Is it ready ? :)

**Comment by Lordmau5** [comment]
Semi-ready. I do have a working pure-javascript copy lying around.
I can upload that to the forked repo later this evening.

However, that will be the last thing that I'm going to update that repo with.
Everything after that will be contributed by the 3 of us as a team on this repo:
https://github.com/Lordmau5/node-spotify-downloader

**Comment by JoseHidalgo** [comment]
I'm OK with that. However, I haven't seen any update from you lately. Your repu was updated on feb. 17, serjum's repo was updated 12 days ago, and your new repo was updated 6 days ago... Am I wrong ? :)

**Comment by Lordmau5** [comment]
Yes, because we're still rewriting some of the code to adept to the new URI system.
Atom, my beloved text editor, decided that it's a good idea to f*ck itself up though (I couldn't type some important characters in it...)
I could fix it yesterday and have been doing work on it on and off (real life stuff is more important, though, so yea...)

**Comment by JoseHidalgo** [comment]
That's OK, I was just checking if I missed something. :) Good luck with Atom ! You may also consider alternatives like Notepad++, etc..

**Comment by Lordmau5** [comment]
Yea, I was a big fan of Notepad++ - It's lightweight and all of that :)
But Atom just had so much more to offer and I liked the design of it :P

Just keep an eye out on the other repo.
We also have a Gitter.im chat, incase you want to chat with us ;)
The link is on the other repo.

**Comment by JoseHidalgo** [comment]
Hey guys,
Just wanted to report complete success with the latest version. The -p and -i handles are really useful. Thank you !
I also wanted to report that the tags aren't saved correctly. When there are several artists, only the first one is saved (example : %artist% = "Zendaya" and %title% = "Something New" when it should be %artist% = "Zendaya; Chris Brown").
The album art isn't saved either.
Just my two cents. :)

**Comment by JoseHidalgo** [comment]
PS : one last suggestion. The songs are saved as %title%.mp3. Could they be saved as %artist% - %title%.mp3 ? Thanks again.

**Comment by Lordmau5** [comment]
https://github.com/Lordmau5/node-spotify-downloader

**Comment by JoseHidalgo** [comment]
Lordmaus, I don't understand your comment. I already downloaded and used that one before posting my comment. I'm not dumb. Thanks.

**Comment by Lordmau5** [comment]
It wasn't meant in an offensive way, but it was merely to say that you should move on over to the other repo and reopen it (or I'll do it, I don't mind) to have a better overview.

I'll delete this repository this evening since it's not needed anymore :)

I'm terribly sorry if I actually offended you in any way with the comment up there

**Comment by JoseHidalgo** [comment]
Great. I'm glad we got this sorted. No problem, we'll continue in the new repo. ;)
